export type TechIconType = { name: string; label: string; icon: string; themeCamo?: boolean };
export const techIcons: TechIconType[] = [
  { name: 'css', label: 'Css', icon: '/tech-icons/css.svg' },
  { name: 'dart', label: 'Dart', icon: '/tech-icons/dart.svg' },
  { name: 'express', label: 'Express', icon: '/tech-icons/express.svg', themeCamo: true },
  { name: 'firebase', label: 'Firebase', icon: '/tech-icons/firebase.svg' },
  { name: 'flutter', label: 'Flutter', icon: '/tech-icons/flutter.svg' },
  { name: 'git', label: 'Git', icon: '/tech-icons/git.svg' },
  { name: 'html', label: 'HTML', icon: '/tech-icons/html.svg' },
  { name: 'javascript', label: 'Javascript', icon: '/tech-icons/javascript.svg' },
  { name: 'mantine', label: 'Mantine', icon: '/tech-icons/mantine.svg' },
  { name: 'mui', label: 'Mui', icon: '/tech-icons/mui.svg' },
  { name: 'mysql', label: 'Mysql', icon: '/tech-icons/mysql.svg' },
  { name: 'nestjs', label: 'Nest.js', icon: '/tech-icons/nestjs.svg' },
  { name: 'nextjs', label: 'Next.js', icon: '/tech-icons/nextjs.svg', themeCamo: true },
  { name: 'nodejs', label: 'Node.js', icon: '/tech-icons/nodejs.svg' },
  { name: 'prisma', label: 'Prisma', icon: '/tech-icons/prisma.svg', themeCamo: true },
  { name: 'reactjs', label: 'React.js', icon: '/tech-icons/reactjs.svg' },
  { name: 'shadcn', label: 'Shadcn', icon: '/tech-icons/shadcn.svg', themeCamo: true },
  { name: 'sqlite', label: 'Sqlite', icon: '/tech-icons/sqlite.svg' },
  { name: 'tailwindcss', label: 'Tailwindcss', icon: '/tech-icons/tailwindcss.svg' },
  { name: 'typescript', label: 'Typescript', icon: '/tech-icons/typescript.svg' },
  { name: 'vite', label: 'Vite', icon: '/tech-icons/vite.svg' },
];
