export const TechIcons: { name: string; icon: string; themeCamo?: boolean }[] = [
  { name: 'css', icon: '/tech-icons/css.svg' },
  { name: 'dart', icon: '/tech-icons/dart.svg' },
  { name: 'express', icon: '/tech-icons/express.svg', themeCamo: true },
  { name: 'firebase', icon: '/tech-icons/firebase.svg' },
  { name: 'flutter', icon: '/tech-icons/flutter.svg' },
  { name: 'git', icon: '/tech-icons/git.svg' },
  { name: 'html', icon: '/tech-icons/html.svg' },
  { name: 'javascript', icon: '/tech-icons/javascript.svg' },
  { name: 'mantine', icon: '/tech-icons/mantine.svg' },
  { name: 'mui', icon: '/tech-icons/mui.svg' },
  { name: 'mysql', icon: '/tech-icons/mysql.svg' },
  { name: 'nestjs', icon: '/tech-icons/nestjs.svg' },
  { name: 'nextjs', icon: '/tech-icons/nextjs.svg', themeCamo: true },
  { name: 'nodejs', icon: '/tech-icons/nodejs.svg' },
  { name: 'prisma', icon: '/tech-icons/prisma.svg', themeCamo: true },
  { name: 'reactjs', icon: '/tech-icons/reactjs.svg' },
  { name: 'shadcn', icon: '/tech-icons/shadcn.svg', themeCamo: true },
  { name: 'sqlite', icon: '/tech-icons/sqlite.svg' },
  { name: 'tailwindcss', icon: '/tech-icons/tailwindcss.svg' },
  { name: 'typescript', icon: '/tech-icons/typescript.svg' },
  { name: 'vite', icon: '/tech-icons/vite.svg' },
];
