import type { Metadata } from 'next';
import { Onest } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/stores/theme';

const onestSans = Onest({
  variable: '--font-onest',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${onestSans.variable} ${onestSans.className} relative h-full w-full antialiased`}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
